<?php
/*
 *     ______            __             __
 *    / ____/___  ____  / /__________  / /
 *   / /   / __ \/ __ \/ __/ ___/ __ \/ /
 *  / /___/ /_/ / / / / /_/ /  / /_/ / /
 *  \______________/_/\__/_/   \____/_/
 *     /   |  / / /_
 *    / /| | / / __/
 *   / ___ |/ / /_
 *  /_/ _|||_/\__/ __     __
 *     / __ \___  / /__  / /____
 *    / / / / _ \/ / _ \/ __/ _ \
 *   / /_/ /  __/ /  __/ /_/  __/
 *  /_____/\___/_/\___/\__/\___/
 *
 * Copyright www.controlaltdelete.dev
 */

declare(strict_types=1);

use ControlAltDelete\NoticeBar\Block\NoticeBar;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var NoticeBar $block */
?>
<div class="controlaltdelete-notice-bar controlaltdelete-notice-bar-<?= $escaper->escapeHtmlAttr($block->getTextAlign()) ?>">
    <?= $block->getText() ?>
</div>
