<?php
/*
 *     ______            __             __
 *    / ____/___  ____  / /__________  / /
 *   / /   / __ \/ __ \/ __/ ___/ __ \/ /
 *  / /___/ /_/ / / / / /_/ /  / /_/ / /
 *  \______________/_/\__/_/   \____/_/
 *     /   |  / / /_
 *    / /| | / / __/
 *   / ___ |/ / /_
 *  /_/ _|||_/\__/ __     __
 *     / __ \___  / /__  / /____
 *    / / / / _ \/ / _ \/ __/ _ \
 *   / /_/ /  __/ /  __/ /_/  __/
 *  /_____/\___/_/\___/\__/\___/
 *
 * Copyright www.controlaltdelete.dev
 */

declare(strict_types=1);

use ControlAltDelete\NoticeBar\Block\NoticeBar;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var NoticeBar $block */

/** text-left text-center text-right */
?>
<div class="controlaltdelete-notice-bar bg-brand-secondary px-2 py-2 text-<?= $escaper->escapeHtmlAttr($block->getTextAlign()) ?> [&_a]:text-white">
    <?= $block->getText() ?>
</div>
