<?php
/*
 *     ______            __             __
 *    / ____/___  ____  / /__________  / /
 *   / /   / __ \/ __ \/ __/ ___/ __ \/ /
 *  / /___/ /_/ / / / / /_/ /  / /_/ / /
 *  \______________/_/\__/_/   \____/_/
 *     /   |  / / /_
 *    / /| | / / __/
 *   / ___ |/ / /_
 *  /_/ _|||_/\__/ __     __
 *     / __ \___  / /__  / /____
 *    / / / / _ \/ / _ \/ __/ _ \
 *   / /_/ /  __/ /  __/ /_/  __/
 *  /_____/\___/_/\___/\__/\___/
 *
 * Copyright www.controlaltdelete.dev
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

$uniqueId = '_' . uniqid();

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menu = $block->getMenuItems() ?: [
    [
        'url' => '/lights.html',
        'name' => 'Lights'
    ],
    [
        'url' => '/t-shirts.html',
        'name' => 'T-Shirts'
    ],
    [
        'url' => '/services.html',
        'name' => 'Services'
    ],
    [
        'url' => '/wled',
        'name' => 'WLED'
    ],
    [
        'url' => '/frequently-asked-questions',
        'name' => 'FAQ'
    ],
];
$block->setData('cache_tags', $viewModelNavigation->getIdentities());
?>

<nav
    class="navigation hidden lg:block order-2 sm:order-1 lg:order-2"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Main menu')) ?>"
    x-data="initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?>()"
    x-ref="nav-desktop"
    @load.window="setActiveMenu($root)"
>
    <ul class="flex flex-wrap gap-x-8">
        <?php foreach ($menu as $item): ?>
            <li>
                <a
                    href="<?= $escaper->escapeUrl($item['url']) ?>"
                    title="<?= $escaper->escapeHtmlAttr($item['name']) ?>"
                    class="level-0 flex py-2 border-b-2 border-transparent hover:border-blue-500
                        aria-[current=page]:font-medium <?= isset($item['isCta']) ? 'text-red-700' : '' ?>"
                >
                    <?= $escaper->escapeHtml($item['name']) ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
</nav>
<script>
    const initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        return {
            setActiveMenu(menuNode) {
                Array.from(this.$root.querySelectorAll('a')).forEach(link => {
                    if (link.href === `${window.location.origin}${window.location.pathname}`) {
                        link.setAttribute('aria-current', 'page');
                    }
                });
            }
        }
    }
</script>
