<?php
/*
 *     ______            __             __
 *    / ____/___  ____  / /__________  / /
 *   / /   / __ \/ __ \/ __/ ___/ __ \/ /
 *  / /___/ /_/ / / / / /_/ /  / /_/ / /
 *  \______________/_/\__/_/   \____/_/
 *     /   |  / / /_
 *    / /| | / / __/
 *   / ___ |/ / /_
 *  /_/ _|||_/\__/ __     __
 *     / __ \___  / /__  / /____
 *    / / / / _ \/ / _ \/ __/ _ \
 *   / /_/ /  __/ /  __/ /_/  __/
 *  /_____/\___/_/\___/\__/\___/
 *
 * Copyright www.controlaltdelete.dev
 */

declare(strict_types=1);

use Magento\Theme\Block\Html\Footer;
use Magento\Framework\Escaper;

/** @var Footer $block */
/** @var Escaper $escaper */
?>
<small class="text-sm text-gray-800 sm:mt-0 mt-4">
    © <?= date('Y'); ?>
    <a
        href="https://www.controlaltdelete.dev/?utm_source=webshop&utm_medium=shop.magedispatch.com&utm_campaign=footer"
        target="_blank"
        rel="noopener noreferrer"
        class="text-gray-700 ml-1"
    >
        Control Alt Delete BV
    </a>
    <?php /* Enable the following line to show the copyright information configured in the admin
    <span><?= $escaper->escapeHtml($block->getCopyright()) ?></span>
    */ ?>
</small>
