<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Theme\Block\Html\Footer;
use Magento\Framework\Escaper;

/** @var Footer $block */
/** @var Escaper $escaper */
?>
<div class="w-full text-center">
    <small class="text-sm text-white">
       Copyright © 2026 Control Alt Delete BV
    </small>
</div>

