<?php
/*
 *     ______            __             __
 *    / ____/___  ____  / /__________  / /
 *   / /   / __ \/ __ \/ __/ ___/ __ \/ /
 *  / /___/ /_/ / / / / /_/ /  / /_/ / /
 *  \______________/_/\__/_/   \____/_/
 *     /   |  / / /_
 *    / /| | / / __/
 *   / ___ |/ / /_
 *  /_/ _|||_/\__/ __     __
 *     / __ \___  / /__  / /____
 *    / / / / _ \/ / _ \/ __/ _ \
 *   / /_/ /  __/ /  __/ /_/  __/
 *  /_____/\___/_/\___/\__/\___/
 *
 * Copyright www.controlaltdelete.dev
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<div class="text-gray-700 body-font bg-container-darker border-t border-container-darker shadow pb-16">
    <div class="container py-8 mx-auto">
        <div class="flex flex-wrap order-first gap-y-16">
            <?php foreach ($block->getChildNames() as $childName): ?>
                <?= $childName !== 'footer-copyright' ? $block->getBlockHtml($childName) : '' ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="bg-container border-t border-b border-container">
        <div class="container py-6 mx-auto flex items-center sm:flex-row flex-col">
            <p>
                <?= $block->getChildHtml('copyright') ?>
            </p>
        </div>
    </div>
</div>

